name: Tests
on:
  push:
    branches:
      - feature/update-ci-functionalities
  pull_request:
    branches:
      - feature/update-ci-functionalities

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/update-ci-functionalities
      - name: Merge changes into develop
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          PR_BRANCH=${{ github.head_ref }}
          echo "Merging changes from branch $PR_BRANCH into develop"
          git fetch origin $PR_BRANCH
          git merge --no-ff origin/$PR_BRANCH
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.15
      - name: Install dependencies
        run: |
          pip install pytest-cov coveralls
          pip install coverage
          pip install -r requirements.txt
          echo requirements installed
        # pip uninstall bson
        # pip uninstall pymongo
        # pip install pymongo
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests with Coverage
        run: |
          coverage run -m pytest tests
          coveralls --service=github-actions
